import { useAdminLayout } from '../../../src/ui/useAdminLayout';
import React, { useCallback, useRef, useState } from 'react';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { ActivityIndicator, FlatList, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getEmployees, type Employee } from '../../../src/core/employees';

const filters = ['All', 'Present', 'On leave', 'Needs review', 'Not checked in'] as const;
type AttendanceStatus = typeof filters[number];
type Shift = { id: string; employeeId: string; date: string; checkIn: string; checkOut: string; branch?: string; shiftName?: string; needsReview?: boolean };
type Leave = { employeeId?: string; type: string; status: string; startDate: string; endDate: string };
type Row = { employee: Employee; shift?: Shift; status: AttendanceStatus; branch: string };
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());

export default function TeamAttendancePage() {
  const { styles, columns, columnWrapperStyle } = useAdminLayout(baseStyles, 'list');
  const router = useRouter();
  const params = useLocalSearchParams<{ branch?: string }>();
  const [branch, setBranch] = useState(typeof params.branch === 'string' ? params.branch : '');
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [shifts, setShifts] = useState<Shift[]>([]);
  const [leaves, setLeaves] = useState<Leave[]>([]);
  const [date, setDate] = useState(today);
  const [filter, setFilter] = useState<AttendanceStatus>('All');
  const [search, setSearch] = useState('');
  const [picker, setPicker] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [attempt, setAttempt] = useState(0);
  const searchRef = useRef<TextInput>(null);

  useFocusEffect(useCallback(() => {
    let active = true;
    setDate(today()); setLoading(true); setError('');
    Promise.all([getEmployees(), AsyncStorage.getItem('branchsuite:team-attendance:v1'), AsyncStorage.getItem('branchsuite:my-attendance-requests:v1')]).then(([team, shiftData, leaveData]) => {
      const recorded: unknown = shiftData === null ? [] : JSON.parse(shiftData);
      const requests: unknown = leaveData === null ? [] : JSON.parse(leaveData);
      if (!Array.isArray(recorded) || !recorded.every(item => item && ['id', 'employeeId', 'date', 'checkIn', 'checkOut'].every(key => typeof item[key] === 'string'))) throw new Error('Team attendance records could not be read.');
      if (!Array.isArray(requests) || !requests.every(item => item && ['type', 'status', 'startDate', 'endDate'].every(key => typeof item[key] === 'string'))) throw new Error('Leave requests could not be read.');
      if (active) { setEmployees(team); setShifts(recorded); setLeaves(requests); }
    }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : 'Could not load team attendance.'); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [attempt]));

  const rows: Row[] = employees.filter(employee => employee.status !== 'inactive').map(employee => {
    const shift = shifts.find(item => item.employeeId === employee.id && item.date === date);
    const onLeave = leaves.some(item => item.employeeId === employee.id && item.type === 'leave' && item.status === 'approved' && item.startDate <= date && item.endDate >= date);
    return { employee, shift, branch: shift?.branch || employee.branch, status: shift?.needsReview ? 'Needs review' : shift?.checkIn ? 'Present' : onLeave ? 'On leave' : 'Not checked in' };
  });
  const branches = [...new Set(rows.map(row => row.branch).filter(Boolean))].sort();
  const scoped = rows.filter(row => !branch || row.branch === branch);
  const visible = scoped.filter(row => (filter === 'All' || row.status === filter) && [row.employee.fullName, row.employee.department, row.branch, row.shift?.shiftName || ''].some(value => value.toLowerCase().includes(search.trim().toLowerCase())));
  const total = (status: AttendanceStatus) => scoped.filter(row => row.status === status).length;
  const count = (value: number) => loading || error ? '—' : String(value);
  const dateLabel = new Date(`${date}T12:00:00+05:30`).toLocaleDateString('en-GB', { timeZone: 'Asia/Kolkata', weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });

  return <SafeAreaView style={styles.safe}><View style={styles.page}>
    <View style={styles.header}><View style={[styles.row, styles.headerIdentity]}><View style={styles.flex}><Text style={styles.companyName}>{/* Your company name */}</Text><Text style={styles.small}>Business workspace</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Focus attendance search" onPress={() => searchRef.current?.focus()} style={styles.headerIcon}><Text style={styles.chevron}>⌕</Text></Pressable><View style={styles.avatar} /></View><View style={styles.headerFilters}><View style={styles.headerFilter}><Text style={styles.small}>Company</Text><Text style={styles.chevron}>⌄</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Choose branch" onPress={() => setPicker(true)} style={[styles.headerFilter, styles.blue]}><Text numberOfLines={1} style={[styles.small, styles.flex]}>{branch || 'All branches'}</Text><Text style={styles.chevron}>⌄</Text></Pressable></View></View>
    <FlatList key={columns} numColumns={columns} columnWrapperStyle={columns > 1 ? columnWrapperStyle : undefined} data={loading || error ? [] : visible} keyExtractor={row => row.employee.id} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.list}
      ListHeaderComponent={<View>
        <View style={styles.titleRow}><Pressable accessibilityRole="button" accessibilityLabel="Back to People" onPress={() => router.replace('/admin/employees/people')} style={styles.back}><Text style={styles.chevron}>‹</Text></Pressable><View style={styles.flex}><Text style={styles.eyebrow}>WORKSPACE</Text><Text style={styles.title}>Team attendance</Text><Text style={styles.subtitle}>{dateLabel}</Text></View></View>
        <View style={styles.branchCard}><View style={styles.dot} /><View style={styles.flex}><Text style={styles.name}>{branch || 'All branches'}</Text><Text style={styles.small}>One branch, every module</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Change branch" onPress={() => setPicker(true)} style={styles.change}><Text style={styles.link}>Change</Text></Pressable></View>
        <View style={styles.coverage}><View style={styles.row}><Text style={styles.coverageTitle}>Today’s coverage</Text><View style={styles.presentBadge}><Text style={styles.presentText}>{count(total('Present'))} present</Text></View></View><View style={styles.track}><View style={[styles.progress, { width: `${!loading && !error && scoped.length ? total('Present') / scoped.length * 100 : 0}%` }]} /></View><View style={styles.legend}>{(['On leave', 'Needs review', 'Not checked in'] as const).map((status, index) => <View key={status} style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: ['#39b8a7', '#e2a348', '#a0aec5'][index] }]} /><Text style={styles.small}>{count(total(status))} {status.toLowerCase()}</Text></View>)}</View></View>
        <View style={styles.searchField}><Text style={styles.searchGlyph}>⌕</Text><TextInput ref={searchRef} accessibilityLabel="Search employee or shift" placeholder="Search employee or shift" placeholderTextColor="#8c96a6" value={search} onChangeText={setSearch} autoCapitalize="none" autoCorrect={false} style={styles.searchInput} /></View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map(label => <Pressable key={label} accessibilityRole="tab" accessibilityLabel={label} accessibilityState={{ selected: filter === label }} onPress={() => setFilter(label)} style={[styles.filter, filter === label && styles.blue]}><Text style={[styles.filterText, filter === label && styles.link]}>{label}</Text></Pressable>)}</ScrollView>
        <Text style={styles.summary}>{count(scoped.length)} employees · {branch || 'All branches'}</Text>
      </View>}
      ListEmptyComponent={loading ? <ActivityIndicator accessibilityLabel="Loading team attendance" color="#345cf2" /> : error ? <View style={styles.card}><Text style={styles.error}>{error}</Text><Pressable accessibilityRole="button" onPress={() => setAttempt(value => value + 1)} style={styles.change}><Text style={styles.link}>Retry</Text></Pressable></View> : <View style={styles.card}><Text style={styles.name}>{rows.length ? 'No matching employees' : 'No team members yet'}</Text><Text style={styles.subtitle}>{rows.length ? 'Try another search, branch or status.' : 'Add employees to see their attendance here.'}</Text></View>}
      renderItem={({ item }) => <View style={[styles.card, styles.listItem]}><View style={styles.row}><View style={styles.initialBadge}><Text style={styles.link}>{item.employee.fullName.split(/\s+/).slice(0, 2).map(part => part.charAt(0)).join('').toUpperCase()}</Text></View><View style={styles.flex}><Text style={styles.name}>{item.employee.fullName}</Text><Text style={styles.subtitle}>{[item.branch, item.employee.department, item.shift?.shiftName].filter(Boolean).join(' · ')}</Text></View><View style={[styles.statusBadge, item.status === 'Present' ? styles.presentBadge : item.status === 'Needs review' ? styles.reviewBadge : item.status === 'On leave' ? styles.leaveBadge : null]}><Text style={styles.statusText}>{item.status}</Text></View></View><View style={styles.times}><Text style={styles.small}>In {item.shift?.checkIn || '—'}</Text><Text style={styles.small}>Out {item.shift?.checkOut || '—'}</Text></View></View>}
    />
    <View style={styles.navigation}>{[{ label: 'Home', icon: '⌂' }, { label: 'CRM', icon: '↗' }, { label: 'People', icon: '♧' }, { label: 'Payroll', icon: '▤' }, { label: 'More', icon: '···' }].map(tab => <Pressable key={tab.label} accessibilityRole="tab" accessibilityLabel={tab.label} accessibilityState={{ selected: tab.label === 'More' }} onPress={tab.label === 'Home' ? () => router.replace('/admin/dashboard') : tab.label === 'People' ? () => router.replace('/admin/employees/people') : tab.label === 'CRM' ? () => router.push('/admin/crm') : tab.label === 'Payroll' ? () => router.push('/admin/payroll') : undefined} style={styles.navItem}><View style={[styles.navIcon, tab.label === 'More' && styles.blue]}><Text style={[styles.navGlyph, tab.label === 'More' && styles.link]}>{tab.icon}</Text></View><Text style={[styles.navLabel, tab.label === 'More' && styles.link]}>{tab.label}</Text></Pressable>)}</View>
  </View><Modal transparent visible={picker} animationType="fade" onRequestClose={() => setPicker(false)}><View style={styles.overlay}><View style={styles.modal}><View style={styles.row}><Text style={styles.coverageTitle}>Choose branch</Text><Pressable accessibilityRole="button" accessibilityLabel="Close branch picker" onPress={() => setPicker(false)} style={styles.back}><Text style={styles.chevron}>×</Text></Pressable></View><ScrollView>{['', ...branches].map(value => <Pressable key={value} accessibilityRole="button" accessibilityLabel={value || 'All branches'} onPress={() => { setBranch(value); setPicker(false); }} style={styles.option}><Text style={styles.name}>{value || 'All branches'}</Text><Text style={styles.link}>{branch === value ? '✓' : ''}</Text></Pressable>)}</ScrollView></View></View></Modal></SafeAreaView>;
}

const baseStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f6f8fd' }, page: { flex: 1, width: '100%', maxWidth: 560, alignSelf: 'center' }, flex: { flex: 1 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 9 },
  header: { padding: 16, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#e4eaf5' }, companyName: { minHeight: 18, fontSize: 14, fontWeight: '800', color: '#20334f' }, small: { fontSize: 9, lineHeight: 16, color: '#8192ad' }, headerIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f5f7fc' }, avatar: { width: 34, height: 34, borderRadius: 12, backgroundColor: '#eaf0ff' }, headerFilters: { flexDirection: 'row', gap: 8, marginTop: 14 }, headerFilter: { flex: 1, minHeight: 34, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, borderRadius: 9, borderWidth: 1, borderColor: '#e4eaf7', backgroundColor: '#f7f9ff' }, chevron: { fontSize: 23, color: '#607591' }, blue: { backgroundColor: '#eaf0ff', borderColor: '#d5dfff' },
  list: { padding: 16, paddingTop: 22, paddingBottom: 28, gap: 12 }, titleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 }, back: { width: 36, height: 36, borderRadius: 10, borderWidth: 1, borderColor: '#e4eaf5', backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, eyebrow: { fontSize: 8, fontWeight: '700', letterSpacing: 2, color: '#8192ad' }, title: { fontSize: 24, fontWeight: '800', color: '#20334f', marginTop: 8, letterSpacing: -0.7 }, subtitle: { fontSize: 11, lineHeight: 18, color: '#7a8ba5', marginTop: 5 }, branchCard: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 12, borderWidth: 1, borderColor: '#e4eaf5', borderRadius: 17, backgroundColor: '#fff', marginTop: 22 }, dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#39b8a7' }, name: { fontSize: 12, fontWeight: '700', color: '#20334f' }, change: { minHeight: 44, paddingHorizontal: 8, justifyContent: 'center' }, link: { fontSize: 10, fontWeight: '600', color: '#345cf2' }, coverage: { borderWidth: 1, borderColor: '#e0e8f5', borderRadius: 18, padding: 18, backgroundColor: '#fff', marginTop: 16 }, coverageTitle: { fontSize: 15, fontWeight: '700', color: '#20334f' }, presentBadge: { backgroundColor: '#e1f3eb', borderRadius: 6, padding: 6 }, presentText: { fontSize: 9, color: '#34856c' }, track: { height: 4, borderRadius: 2, backgroundColor: '#e8edf5', marginTop: 16, overflow: 'hidden' }, progress: { height: 4, backgroundColor: '#138f80' }, legend: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 12 }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 }, legendDot: { width: 5, height: 5, borderRadius: 3 },
  searchField: { marginTop: 14, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#e1e8f4', backgroundColor: '#fff', borderRadius: 13, paddingHorizontal: 13, minHeight: 46 }, searchGlyph: { fontSize: 22, color: '#7a8ba5', marginRight: 9 }, searchInput: { flex: 1, minWidth: 0, paddingVertical: 12, fontSize: 13, color: '#20334f' }, filters: { gap: 7, paddingVertical: 12 }, filter: { minHeight: 40, paddingHorizontal: 12, justifyContent: 'center', borderWidth: 1, borderColor: '#e4eaf5', backgroundColor: '#fff', borderRadius: 12 }, filterText: { fontSize: 10, fontWeight: '600', color: '#405573' }, summary: { fontSize: 10, color: '#8192ad', marginTop: 4, marginBottom: 3 }, card: { padding: 16, borderWidth: 1, borderColor: '#e0e8f5', borderRadius: 17, backgroundColor: '#fff' }, initialBadge: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#e8eeff', alignItems: 'center', justifyContent: 'center' }, statusBadge: { padding: 6, borderRadius: 6, backgroundColor: '#edf0f6' }, statusText: { fontSize: 9, color: '#52627c' }, reviewBadge: { backgroundColor: '#fff1d9' }, leaveBadge: { backgroundColor: '#eee7ff' }, times: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#f0f3f9', paddingTop: 10, marginTop: 14 }, error: { fontSize: 12, color: '#b94d61' },
  navigation: { flexDirection: 'row', paddingVertical: 8, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#e4eaf5' }, navItem: { flex: 1, alignItems: 'center', gap: 3 }, navIcon: { width: 46, height: 32, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, navGlyph: { fontSize: 22, color: '#71829c' }, navLabel: { fontSize: 9, color: '#71829c' }, overlay: { flex: 1, padding: 24, justifyContent: 'center', backgroundColor: 'rgba(27,43,68,0.3)' }, modal: { padding: 22, width: '100%', maxWidth: 460, maxHeight: '85%', alignSelf: 'center', borderRadius: 20, backgroundColor: '#fff' }, option: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 17, borderBottomWidth: 1, borderBottomColor: '#edf1f8' },
});
