import { StyleSheet } from 'react-native';
import { colors } from './data';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  shell: { flex: 1, flexDirection: "row" },
  flex: { flex: 1 },
  sidebar: {
    width: 224,
    backgroundColor: "#FCFDFF",
    borderRightWidth: 1,
    borderColor: colors.border,
    padding: 22,
    paddingTop: 28,
  },
  brandIcon: {
    width: 36,
    height: 36,
    backgroundColor: colors.primary,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  brandSymbol: { fontSize: 25, color: "white" },
  brand: { fontSize: 17, color: colors.ink, fontWeight: "700" },
  caption: {
    fontSize: 10,
    color: colors.muted,
    letterSpacing: 1.3,
    marginBottom: 18,
  },
  sideItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 13,
    borderRadius: 12,
    marginBottom: 7,
  },
  sideActive: {
    backgroundColor: "#E5F3ED",
    borderLeftWidth: 3,
    borderLeftColor: "#7FB5A1",
  },
  sideSymbol: { fontSize: 23, color: colors.muted },
  sideLabel: { color: colors.muted, fontSize: 13 },
  sideFooter: { marginTop: "auto", paddingTop: 30 },
  topbar: {
    minHeight: 70,
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  topbarCompact: {
    flexWrap: "wrap",
    paddingTop: 10,
    paddingBottom: 10,
  },
  topbarMeta: { minWidth: 0, flexShrink: 1 },
  topbarActions: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "#DAF1EC",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 13, fontWeight: "700", color: "#146F65" },
  searchButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#F5F7FB",
    alignItems: "center",
    justifyContent: "center",
  },
  searchSymbol: { fontSize: 29, color: colors.ink },
  content: { padding: 20, paddingBottom: 32 },
  title: {
    fontSize: 29,
    fontWeight: "700",
    letterSpacing: -0.8,
    color: colors.ink,
  },
  subtitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 21,
    marginTop: 5,
    marginBottom: 18,
  },
  greeting: {
    paddingBottom: 18,
  },
  greetingSubtitle: { fontSize: 12, color: colors.muted, lineHeight: 19, marginTop: 4 },
  eyebrow: {
    fontSize: 10,
    color: "#35877A",
    letterSpacing: 1.2,
    fontWeight: "600",
  },
  hello: {
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: -0.8,
    color: colors.ink,
    marginTop: 0,
  },
  columns: { gap: 22 },
  desktopColumns: { flexDirection: "row", gap: 25 },
  column: { flex: 1, gap: 12, minWidth: 0 },
  card: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 18,
  },
  signOut: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
  },
  documentBack: { width: 38, height: 38, borderRadius: 10, backgroundColor: "white", borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
  documentBadge: { backgroundColor: "#EFF2F7", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 6 },
  documentBadgeText: { fontSize: 10, color: colors.muted, fontWeight: "600" },
  documentPreview: { minHeight: 44, borderWidth: 1, borderColor: colors.border, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  documentButtonText: { fontSize: 13, fontWeight: "700", color: colors.ink },
  createLetter: { minHeight: 48, backgroundColor: "#E9EEFF", borderRadius: 12, alignItems: "center", justifyContent: "center", marginTop: 12, paddingHorizontal: 12 },
  leavePage: { width: '100%', maxWidth: 960, alignSelf: 'center', gap: 20 },
  leaveEyebrow: { fontSize: 10, fontWeight: '700', letterSpacing: 1.2, color: '#6C7788', marginBottom: 10 },
  leaveTitle: { fontSize: 28, lineHeight: 34, fontWeight: '700', letterSpacing: -0.8, color: colors.ink },
  leaveSubtitle: { fontSize: 14, lineHeight: 22, color: '#657382', marginTop: 8 },
  leaveApply: { minHeight: 44, paddingHorizontal: 16, borderRadius: 13, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  leaveBalances: { flexDirection: 'row', gap: 12, marginTop: 2 },
  leaveBalanceCard: { flex: 1, minWidth: 0, backgroundColor: 'white', borderWidth: 1, borderColor: colors.border, borderRadius: 17, padding: 15, gap: 10 },
  leaveBalanceLabel: { flexShrink: 1, fontSize: 12, lineHeight: 18, color: '#657382' },
  leaveBalanceValue: { fontSize: 25, lineHeight: 30, fontWeight: '700', letterSpacing: -0.6, color: colors.ink },
  leaveBalanceHint: { fontSize: 11, lineHeight: 17, color: '#657382' },
  leaveNotice: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, backgroundColor: '#ECF0FF', borderRadius: 14, padding: 16 },
  leaveNoticeText: { flex: 1, fontSize: 13, lineHeight: 20, color: '#4E6484' },
  leaveRequests: { gap: 15, marginTop: 4 },
  leaveRequestsTitle: { fontSize: 20, lineHeight: 27, fontWeight: '700', color: colors.ink },
  leaveRequestCard: { backgroundColor: 'white', borderWidth: 1, borderColor: colors.border, borderRadius: 20, padding: 16, gap: 12 },
  leaveRequestAvatar: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#DEF5EF', alignItems: 'center', justifyContent: 'center' },
  leaveRequestInitials: { color: '#146F65', fontSize: 15, fontWeight: '700' },
  leaveEmployeeName: { fontSize: 15, lineHeight: 21, fontWeight: '700', color: colors.ink },
  leaveRequestType: { fontSize: 13, lineHeight: 20, color: '#657382', marginTop: 3 },
  leaveStatus: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 9, backgroundColor: '#FFF1DA' },
  leaveStatusApproved: { backgroundColor: '#E2F4EC' },
  leaveStatusCancelled: { backgroundColor: '#EFF2F7' },
  leaveStatusText: { fontSize: 10, fontWeight: '700', color: '#945F16' },
  leaveRequestDates: { fontSize: 13, lineHeight: 20, fontWeight: '700', color: colors.ink, marginTop: 6 },
  leaveRequestReason: { fontSize: 14, lineHeight: 21, color: '#657382' },
  leaveCancel: { minHeight: 44, borderRadius: 14, borderWidth: 1, borderColor: '#D8E0E4', alignItems: 'center', justifyContent: 'center', padding: 10, marginTop: 4 },
  leaveCancelText: { fontSize: 13, fontWeight: '700', color: '#3C4A5A' },
  leaveFooter: { fontSize: 11, lineHeight: 18, marginTop: 36 },
  leaveConfirmationContent: { paddingTop: 12, gap: 22 },
  leaveConfirmationActions: { flexDirection: 'row', gap: 10 },
  leaveConfirmationCancel: { minHeight: 50, borderRadius: 14, borderWidth: 1, borderColor: '#D8E0E4', alignItems: 'center', justifyContent: 'center', padding: 12 },
  shiftCard: { borderRadius: 23, borderColor: "#D9EAE2", backgroundColor: "#F7FCF9", padding: 22 },
  row: { flexDirection: "row", alignItems: "center", gap: 10 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  cardTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 21,
  },
  small: { color: colors.muted, fontSize: 12, lineHeight: 19 },
  body: { color: colors.ink, fontSize: 14, lineHeight: 21 },
  bold: { color: colors.ink, fontWeight: "700" },
  icon: {
    width: 41,
    height: 41,
    borderRadius: 13,
    backgroundColor: "#E2F6F0",
    alignItems: "center",
    justifyContent: "center",
  },
  iconText: { fontSize: 25, color: "#167E6C" },
  badge: {
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  badgeText: { fontSize: 10, fontWeight: "600" },
  times: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginVertical: 20,
    paddingVertical: 17,
    paddingHorizontal: 15,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#E2EDE7",
    borderRadius: 15,
  },
  time: { fontSize: 26, fontWeight: "700", color: colors.ink, marginTop: 5 },
  timeLine: { flex: 0.7, height: 1, backgroundColor: "#E0EAE8" },
  button: {
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
  },
  secondary: { backgroundColor: "#E5F3ED" },
  buttonText: { color: "white", fontWeight: "700", fontSize: 14 },
  localHint: {
    textAlign: "center",
    color: colors.muted,
    fontSize: 10,
    lineHeight: 17,
    marginTop: 13,
  },
  tile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 15,
    padding: 16,
    minHeight: 86,
    marginBottom: 1,
  },
  chevron: { color: "#9AA6B8", fontSize: 26 },
  metrics: { flexDirection: "row", gap: 10 },
  metric: {
    flex: 1,
    minWidth: 0,
    borderRadius: 16,
    padding: 16,
    minHeight: 154,
    borderWidth: 1,
    borderColor: colors.border,
  },
  metricLabel: { fontSize: 11, color: colors.muted, marginTop: 14 },
  metricValue: {
    fontSize: 28,
    fontWeight: "700",
    letterSpacing: -0.8,
    color: colors.ink,
    marginTop: 8,
    marginBottom: 7,
  },
  section: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 2,
  },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: colors.ink },
  link: { color: colors.primary, fontSize: 12, fontWeight: "600", padding: 8 },
  taskCard: { marginBottom: 2 },
  footer: {
    color: "#7C8E9C",
    fontSize: 10,
    textAlign: "center",
    marginTop: 30,
  },
  bottomNav: {
    flexDirection: "row",
    backgroundColor: "white",
    borderTopWidth: 1,
    borderColor: colors.border,
    padding: 7,
    gap: 3,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 7,
    borderRadius: 12,
    gap: 3,
  },
  navActive: { backgroundColor: "#E5F3ED" },
  navSymbol: { fontSize: 24, color: colors.muted },
  navLabel: { color: colors.muted, fontSize: 10 },
  summary: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderRadius: 16,
    marginBottom: 16,
  },
  taskSummaryItem: { flex: 1, minWidth: 0 },
  taskSummaryValue: {
    color: colors.ink,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "700",
  },
  taskSummaryLabel: {
    color: colors.muted,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 2,
  },
  taskSummaryDivider: {
    width: 1,
    height: 36,
    backgroundColor: colors.border,
    marginRight: 10,
  },
  chips: { flexDirection: "row", gap: 8, paddingBottom: 14 },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 8,
    backgroundColor: "white",
  },
  chipSelected: { backgroundColor: "#E2F4EC", borderColor: "#8EBBAF" },
  payValue: {
    fontSize: 42,
    color: colors.ink,
    fontWeight: "700",
    marginTop: 15,
  },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 20 },
  detail: { gap: 4, marginBottom: 12 },
  overlay: {
    flex: 1,
    backgroundColor: "#17263F88",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modal: {
    backgroundColor: "white",
    borderRadius: 22,
    padding: 22,
    width: "100%",
    maxWidth: 560,
    maxHeight: "90%",
  },
  documentOverlay: { flex: 1, justifyContent: "flex-end", alignItems: "center", padding: 10 },
  documentBackdrop: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "#23394D60" },
  documentSheet: { width: "100%", maxWidth: 560, maxHeight: "90%", backgroundColor: "white", borderRadius: 26, paddingHorizontal: 24, paddingBottom: 24 },
  documentHandle: { width: 40, height: 4, borderRadius: 4, backgroundColor: "#D6DFE9", alignSelf: "center", marginTop: 14, marginBottom: 22 },
  documentSheetTitle: { flex: 1, fontSize: 21, lineHeight: 29, fontWeight: "700", color: colors.ink },
  documentSheetClose: { width: 44, height: 44, borderRadius: 14, backgroundColor: "#F5F6FA", alignItems: "center", justifyContent: "center" },
  documentSheetContent: { gap: 20, paddingTop: 20 },
  documentEmployee: { fontSize: 14, lineHeight: 21, color: colors.muted },
  documentNotice: { flexDirection: "row", alignItems: "flex-start", gap: 12, borderRadius: 14, backgroundColor: "#EAF1FF", padding: 16 },
  documentNoticeIcon: { width: 16, height: 16, borderWidth: 1.5, borderColor: "#456485", borderRadius: 8, alignItems: "center", justifyContent: "center", marginTop: 3 },
  documentNoticeIconText: { color: "#456485", fontSize: 11, fontWeight: "700", lineHeight: 13 },
  documentNoticeText: { flex: 1, color: "#456485", fontSize: 14, lineHeight: 21 },
  documentSave: { minHeight: 50, borderRadius: 14, backgroundColor: "#007D73", alignItems: "center", justifyContent: "center", padding: 12 },
  close: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: { color: colors.muted, fontSize: 28 },
  field: { marginBottom: 16 },
  label: {
    fontSize: 12,
    color: colors.ink,
    fontWeight: "600",
    marginBottom: 7,
  },
  input: {
    borderWidth: 1,
    borderColor: "#CDDCD7",
    borderRadius: 11,
    padding: 13,
    fontSize: 14,
    color: colors.ink,
    backgroundColor: "#FBFDFC",
    minHeight: 46,
  },
  error: { color: "#B3293E", fontSize: 12, lineHeight: 19, marginBottom: 16 },
  moneyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 10,
  },
  total: { borderTopWidth: 1, borderColor: colors.border, marginTop: 10 },
  toast: {
    position: "absolute",
    left: 20,
    right: 20,
    maxWidth: 500,
    alignSelf: "center",
    backgroundColor: "#17263F",
    borderRadius: 13,
    padding: 16,
  },
  toastText: { color: "white", textAlign: "center", fontSize: 13 },
});
